site_name: Tech Notes

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: yellow
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: yellow
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.expand
    - navigation.indexes

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/squidfunk/mkdocs-material
  generator: false

# nav template for 3 level
#nav:
#- Home: index.md
#- Software Installation:
#  - Overview: software/overview.md
#  - VS Code: software/vscode.md
#- Python:
#  - Getting Started:
#    - Installation: python/getting-started/installation.md
#    - Basic Syntax: python/getting-started/syntax.md
#  - Advanced Topics:
#    - Decorators: python/advanced/decorators.md
#    - Generators: python/advanced/generators.md
#- AI:
#  - Machine Learning:
#    - Basics: ai/ml/basics.md
#    - Neural Networks: ai/ml/neural-networks.md
#  - Deep Learning:
#    - CNN: ai/dl/cnn.md
#    - RNN: ai/dl/rnn.md

nav:
- Home: index.md
- Software:
  - MkDocs: software/mkdocs.md
  - Docker: software/docker.md
  - Docker 安裝指南 - Ubuntu: software/docker-ubuntu-install-zh.md
  - Installing Ollama with Docker: software/ollama-docker-installation-guide.md
- Python:
  - Python Overview: python/overview.md
  - Python 概覽: python/overview-zh.md
  - FastAPI: python/fastapi.md